# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from confirm_add import ConfirmAddUI
from db_manager import DBManager

# Add New User Screen
class AddUserUI(QDialog):

    def __init__(self):
        # This is needed here to inherit methods and data from QMainWindow
        super().__init__()
        self.setup_ui(self)  # This method was provided by PyQt Designer. Note the snake_case update
        self.retranslate_ui(self)  # This method was provided by PyQt Designer. Note the snake_case update\
        self.db = DBManager('..')

    def setup_ui(self, add_student):
        add_student.setObjectName("add_student")
        add_student.resize(377, 268)
        add_student.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.title_txt = QtWidgets.QLabel(add_student)
        self.title_txt.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.title_txt.setObjectName("title_txt")
        self.first_txt = QtWidgets.QLabel(add_student)
        self.first_txt.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.first_txt.setObjectName("first_txt")
        self.last_txt = QtWidgets.QLabel(add_student)
        self.last_txt.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.last_txt.setObjectName("last_txt")
        self.year_txt = QtWidgets.QLabel(add_student)
        self.year_txt.setGeometry(QtCore.QRect(20, 170, 101, 16))
        self.year_txt.setObjectName("year_txt")
        self.hline = QtWidgets.QFrame(add_student)
        self.hline.setGeometry(QtCore.QRect(20, 40, 361, 16))
        self.hline.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline.setObjectName("hline")

        # Receives the user information on student to be added
        self.first_entry = QtWidgets.QLineEdit(add_student)
        self.first_entry.setGeometry(QtCore.QRect(130, 70, 171, 20))
        self.first_entry.setObjectName("first_entry")
        self.last_entry = QtWidgets.QLineEdit(add_student)
        self.last_entry.setGeometry(QtCore.QRect(130, 120, 171, 20))
        self.last_entry.setObjectName("last_entry")
        self.year_entry = QtWidgets.QLineEdit(add_student)
        self.year_entry.setGeometry(QtCore.QRect(130, 170, 171, 20))
        self.year_entry.setObjectName("year_entry")

        self.ok_btn = QtWidgets.QPushButton(add_student)
        self.ok_btn.clicked.connect(self.user_added)            # Opens Confirmation window of user added
        self.ok_btn.setGeometry(QtCore.QRect(200, 220, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ok_btn.setFont(font)
        self.ok_btn.setStyleSheet("background-color: rgb(85, 170, 255);\n""font: 10pt \"MS Shell Dlg 2\";\n""border-radius:8px;\n""color:white;\n""")
        self.ok_btn.setObjectName("ok_btn")

        self.cancel_btn = QtWidgets.QPushButton(add_student)
        self.cancel_btn.clicked.connect(self.close)             # Closes window when clicked
        self.cancel_btn.setGeometry(QtCore.QRect(280, 220, 75, 31))
        self.cancel_btn.setStyleSheet("background-color: rgb(85, 170, 255);\n""font: 10pt \"MS Shell Dlg 2\";\n""border-radius:8px;\n""color:white;")
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslate_ui(add_student)
        QtCore.QMetaObject.connectSlotsByName(add_student)

    def retranslate_ui(self, add_student):
        _translate = QtCore.QCoreApplication.translate
        add_student.setWindowTitle(_translate("add_student", "Add Student"))
        self.title_txt.setText(_translate("add_student", "<html><head/><body><p><span style=\" font-size:10pt;\">Add Student</span></p></body></html>"))
        self.first_txt.setText(_translate("add_student", "<html><head/><body><p><span style=\" font-size:10pt;\">First Name</span></p></body></html>"))
        self.last_txt.setText(_translate("add_student", "<html><head/><body><p><span style=\" font-size:10pt;\">Last Name</span></p></body></html>"))
        self.year_txt.setText(_translate("add_student", "<html><head/><body><p><span style=\" font-size:10pt;\">Admittance Year</span></p></body></html>"))
        self.ok_btn.setText(_translate("add_student", "Submit"))
        self.cancel_btn.setText(_translate("add_student", "Cancel"))

    # When called prompts the confirmation screen and adds student to the db
    def user_added(self):
        # Gets data from current lineedit text for user data
        record = [self.first_entry.text(), self.last_entry.text(), self.year_entry.text()]

        # Checks if user left field empty, doesnt add to db if field empty
        if '' in record:
            name = None
        else:
            self.db.open_connection()
            self.db.add_record(record)
            self.db.close_connection()

            name = [self.first_entry.text(), self.last_entry.text()]
            self.first_entry.clear()
            self.last_entry.clear()
            self.year_entry.clear()

        # Confirmation screen with users name in text
        confirm = ConfirmAddUI(name)
        confirm.show()
        confirm.exec_()
