# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

# Confirmation Popup screen for adding user
class ConfirmAddUI(QDialog):

    def __init__(self, name):
        # This is needed here to inherit methods and data from QMainWindow
        super().__init__()
        self.setup_ui(self)  # This method was provided by PyQt Designer. Note the snake_case update
        self.retranslate_ui(self)  # This method was provided by PyQt Designer. Note the snake_case update

        # Prints error message if field missing, else prints confirmation
        if name is None:
            self.confirmation.setText("Unable to add Student")
            self.show_name.setText("Please fill out all fields")
        else:
            self.full_name = name[0] + ' ' + name[1]
            self.show_name.setText("Thank you, A record for " + self.full_name + " has been added")

    def setup_ui(self, confirm_box):
        confirm_box.setObjectName("confirm_box")
        confirm_box.resize(413, 160)
        font = QtGui.QFont()
        font.setPointSize(10)
        confirm_box.setFont(font)
        self.confirmation = QtWidgets.QLabel(confirm_box)
        self.confirmation.setGeometry(QtCore.QRect(20, 20, 201, 21))
        self.confirmation.setObjectName("confirmation")
        self.show_name = QtWidgets.QLabel(confirm_box)
        self.show_name.setGeometry(QtCore.QRect(20, 70, 381, 16))
        self.show_name.setObjectName("show_name")
        self.hline = QtWidgets.QFrame(confirm_box)
        self.hline.setGeometry(QtCore.QRect(10, 40, 401, 16))
        self.hline.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline.setObjectName("hline")

        self.ok_btn = QtWidgets.QPushButton(confirm_box)
        self.ok_btn.clicked.connect(self.close)
        self.ok_btn.setGeometry(QtCore.QRect(314, 120, 71, 23))
        self.ok_btn.setStyleSheet("background-color: rgb(85, 170, 255);\n""font: 10pt \"MS Shell Dlg 2\";\n""border-radius:8px;\n""color:white;")
        self.ok_btn.setObjectName("OK")

        self.retranslate_ui(confirm_box)
        QtCore.QMetaObject.connectSlotsByName(confirm_box)

    def retranslate_ui(self, confirm_box):
        _translate = QtCore.QCoreApplication.translate
        confirm_box.setWindowTitle(_translate("confirm_box", "Addition Status"))
        self.confirmation.setText(_translate("confirm_box", "<html><head/><body><p><span style=\" font-size:12pt;\">Record Added Successfully</span></p></body></html>"))
        self.show_name.setText(_translate("confirm_box", "<html><head/><body><p><span style=\" font-size:10pt;\">Thank you, Successfully added student to the system</span></p></body></html>"))
        self.ok_btn.setText(_translate("confirm_box", "OK"))
