# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from db_manager import DBManager

# Search by Student Name window
class UINameSearch(QDialog):
    def __init__(self):
        self.db = DBManager('..')
        super().__init__()
        self.setup_ui(self)
        self.retranslate_ui(self)

        self.name_entry.returnPressed.connect(self.update_table)       # When user presses enter on search, updates table

    def setup_ui(self, name_search):
        name_search.setObjectName("name_search")
        name_search.resize(665, 451)
        name_search.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_entry = QtWidgets.QLineEdit(name_search)
        self.name_entry.setGeometry(QtCore.QRect(170, 60, 451, 21))
        self.name_entry.setObjectName("name_entry")
        self.title = QtWidgets.QLabel(name_search)
        self.title.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.title.setObjectName("title")
        self.hline = QtWidgets.QFrame(name_search)
        self.hline.setGeometry(QtCore.QRect(10, 30, 641, 16))
        self.hline.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline.setObjectName("hline")
        self.name_txt = QtWidgets.QLabel(name_search)
        self.name_txt.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.name_txt.setObjectName("label_2")
        self.db_table = QtWidgets.QTableWidget(name_search)
        self.db_table.setGeometry(QtCore.QRect(30, 110, 591, 271))
        self.db_table.setObjectName("db_table")
        self.db_table.setColumnCount(6)
        self.db_table.setHorizontalHeaderLabels(('Student ID', 'First Name', 'Last Name', 'Email', 'Admittance Year', 'Photo'))
        self.db_table.setRowCount(0)

        self.exit_btn = QtWidgets.QPushButton(name_search)
        self.exit_btn.setAutoDefault(False)
        self.exit_btn.clicked.connect(self.close)
        self.exit_btn.setGeometry(QtCore.QRect(560, 400, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                    "font: 85 12pt \"MS Shell Dlg 2\";\n"
                                    "border-radius:8px;\n"
                                    "color:white;\n""")
        self.exit_btn.setObjectName("exit_btn")

        self.retranslate_ui(name_search)
        QtCore.QMetaObject.connectSlotsByName(name_search)

    def retranslate_ui(self, name_search):
        _translate = QtCore.QCoreApplication.translate
        name_search.setWindowTitle(_translate("name_search", "Search by Name"))
        self.title.setText(_translate("name_search", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Search by Name</span></p></body></html>"))
        self.name_txt.setText(_translate("name_search", "<html><head/><body><p><span style=\" font-size:10pt;\">Student Name</span></p></body></html>"))
        self.exit_btn.setText(_translate("name_search", "Exit"))

    # Updates the table widget with the SQL query by name
    def update_table(self):
        self.db.open_connection()

        # Resets the table widget to empty
        self.db_table.clear()
        self.db_table.setRowCount(0)

        users = self.db.search_by_name(self.name_entry.text())          # Searches db by name supplied by user

        # Loops through list of results and adds to table widget
        for row, row_data in enumerate(users):
            self.db_table.insertRow(row)
            for col, data in enumerate(row_data):
                self.db_table.setItem(row, col, QtWidgets.QTableWidgetItem(str(data)))

        # Adds column titles to table
        self.db_table.setHorizontalHeaderLabels(('Student ID', 'First Name', 'Last Name', 'Email', 'Admittance Year', 'Photo'))
        self.db.close_connection()
